name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Check the [ROADMAP](https://github.com/salazarsebas/stellar-zk/blob/main/ROADMAP.md) for already-planned features.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of the feature.
      placeholder: What would you like to see added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use case
      description: Why is this feature important? What problem does it solve?
      placeholder: |
        I'm trying to ... but currently ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution (optional)
      description: If you have ideas on how this could be implemented, describe them here.

  - type: dropdown
    id: backend
    attributes:
      label: Related backend(s)
      description: Which backend(s) does this feature relate to?
      multiple: true
      options:
        - groth16
        - ultrahonk
        - risc0
        - core (all backends)
        - CLI
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.
